version: "3.8"

services:
  mysql:
    image: mysql:8.3
    container_name: mysqldb
    restart: always
    ports:
      - "3307:3306"   # se você NÃO tiver outro MySQL local usando 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: visusdb
      MYSQL_USER: visus
      MYSQL_PASSWORD: ^85Q!ojge4s   # pode trocar depois por variável de ambiente
    networks:
      - mysql-network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "18080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysqldb
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge