version: "3.8"

services:
  mysql:
    image: mysql:8.3
    container_name: mysqldb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - mysql-network

#Para ver o banco pode usar o adminer ou phpmyadmin, voces escolhem! é só descomentar o que voces quiserem



  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "18080:8080"
    networks:
      - mysql-network

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: phpmyadmin
#    ports:
#      - "18081:80"
#    environment:
#      PMA_HOST: mysqldb
#      MYSQL_ROOT_PASSWORD: root
#    networks:
#      - mysql-network

networks:
  mysql-network:
    driver: bridge
